<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <PlatformTarget>x64</PlatformTarget>
        <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
        <Title>$(AssemblyName)</Title>
        <LangVersion>latest</LangVersion>
        <Version>1.1.5.2</Version>
        <Platforms>x64</Platforms>
        <EnableWindowsTargeting>true</EnableWindowsTargeting>
        <NeutralLanguage>en-US</NeutralLanguage>
        <AnalysisLevel>latest-recommended</AnalysisLevel>
        <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
        <IsTrimmable>True</IsTrimmable>
        <WarningLevel>9999</WarningLevel>
        <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
        <VersionSuffix>-testing</VersionSuffix>
        <DebugType>embedded</DebugType>
        <TreatWarningsAsErrors>True</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
        <IsTrimmable>True</IsTrimmable>
        <WarningLevel>1</WarningLevel>
        <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
        <DebugType>none</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Dism" Version="5.0.0" />
        <PackageReference Include="System.Management" Version="10.0.5" />
    </ItemGroup>

</Project>
