@ECHO off

IF EXIST "BUILD" (
    DEL /S /Q "BUILD"
)
IF EXIST "CONSOLEAPP\BIN" (
    DEL /S /Q "CONSOLEAPP\BIN"
)

IF EXIST "CONSOLEAPP\OBJ" (
    DEL /S /Q "CONSOLEAPP\OBJ"
)

IF %ERRORLEVEL%==0 (
    EXIT
) ELSE (
    ECHO.PROGRAM EXITED WITH CODE %ERRORLEVEL%
    EXIT /B %ERRORLEVEL%
)
